"""empty message

Revision ID: 80c1060f2add
Revises: 
Create Date: 2020-06-07 19:32:41.561102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80c1060f2add'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('identifier', sa.String(length=36), nullable=True))
    op.create_unique_constraint(None, 'actors', ['identifier'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'actors', type_='unique')
    op.drop_column('actors', 'identifier')
    # ### end Alembic commands ###
