"""empty message

Revision ID: c16edd5f2ba3
Revises: 80c1060f2add
Create Date: 2020-06-07 20:21:03.095319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c16edd5f2ba3'
down_revision = '80c1060f2add'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('gender', sa.CHAR(length=1), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actors', 'gender')
    # ### end Alembic commands ###
