"""empty message

Revision ID: ce17fab19a2a
Revises: f8fe1ef7f5a2
Create Date: 2020-06-10 09:29:53.903301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce17fab19a2a'
down_revision = 'f8fe1ef7f5a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('production_house', sa.String(length=50), nullable=True))
    op.drop_column('movies', 'production_houese')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('production_houese', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('movies', 'production_house')
    # ### end Alembic commands ###
