"""empty message

Revision ID: f8fe1ef7f5a2
Revises: c16edd5f2ba3
Create Date: 2020-06-10 09:27:53.623412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8fe1ef7f5a2'
down_revision = 'c16edd5f2ba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actors', 'gender',
               existing_type=sa.CHAR(length=1),
               nullable=False)
    op.add_column('movies', sa.Column('identifier', sa.String(length=36), nullable=True))
    op.add_column('movies', sa.Column('ott_partner', sa.String(length=20), nullable=True))
    op.add_column('movies', sa.Column('production_houese', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'movies', ['identifier'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movies', type_='unique')
    op.drop_column('movies', 'production_houese')
    op.drop_column('movies', 'ott_partner')
    op.drop_column('movies', 'identifier')
    op.alter_column('actors', 'gender',
               existing_type=sa.CHAR(length=1),
               nullable=True)
    # ### end Alembic commands ###
